### ISSUE TITLE
FE - Create foundation

### ISSUE THREAD

**Issue by yusufseyrek** [SwarmMarkets/quickbuy-frontend#1]
**Story**
A micro FE package needs to be created for the quickbuy app.

**TODOs**
- [ ] Create quickbuy FE project
- [ ] Push project repo to origin
- [ ] Add dependencies and architect the following tech stack; React, Typescript, Styled Components, Redux, Jest
