### ISSUE TITLE
FE - Add quickbuy page to router

### ISSUE THREAD

**Issue by yusufseyrek** [SwarmMarkets/quickbuy-frontend#2]
**Story**
For navigating and deep linking in quickbuy project, there should be a routing mechanism.

**TODOs**
- [x] Add quickbuy component folder to project
- [x] Add a new path(/quickbuy) 
- [x] Add a child router under quickbuy route
