### ISSUE TITLE
FE - Create Buy instantly page UI

### ISSUE THREAD

**Issue by yusufseyrek** [SwarmMarkets/quickbuy-frontend#3]
**Story**
To be able to have a kick start on FE and connect BE later, dummy UI components needs to be created first.

**TODOs**
- [ ] Create necessary UI elements
- [ ] Compose the page
- [ ] Make sure its responsive
