### ISSUE TITLE
FE - Create Payment methods page UI

### ISSUE THREAD

**Issue by yusufseyrek** [SwarmMarkets/quickbuy-frontend#4]
**Story**
To be able to have a kick start on FE and connect BE later, dummy UI components needs to be created first.

**TODOs**

- [ ] Create dummy payment methods page container
- [ ] Add necessary UI elements (not CC info inputs)
- [ ] Connect to router
