### ISSUE TITLE
FE - Add Yoti Connect

### ISSUE THREAD

**Issue by yusufseyrek** [SwarmMarkets/quickbuy-frontend#5]
**Story**
For user verification, a Yoti connect flow has to be introduced to project.

**TODOs**
- [ ] Add Yoti JS client dependency to the project
- [ ] Add Yoti Connect button to the Buy Instantly page
- [ ] Implement Yoti callback function and make sure that flow works as expected
