### ISSUE TITLE
FE - Add Fiat to Cryptocurrency conversion logic

### ISSUE THREAD

**Issue by yusufseyrek** [SwarmMarkets/quickbuy-frontend#6]
**Story**
In the design of buy instantly page, when you enter a price; it shows the cryptocurrency amount below.

**TODOs**
- [ ] Add a network request which gets the fiat to crypto conversion
- [ ] Show conversion on the UI
- [ ] Conversion re-fetch update amount in every second
