### ISSUE TITLE
FE - Create Vouchers page UI

### ISSUE THREAD

**Issue by yusufseyrek** [SwarmMarkets/quickbuy-frontend#7]
**Story**
To be able to have a kick start on FE and connect BE later, dummy UI components needs to be created first.

**TODOs**
- [ ] Create Voucher card element
- [ ] Add UI actions
- [ ] Compose the list page
